### ISSUE TITLE
Request : Enemy expension

### ISSUE THREAD

**Issue by d0ob** [Yousei9/Factorio-UI_Hotkeys#2]
Hi there !

Are you open to requests by chance ? =}
If yes, I wonder if the debug "show-enemy-expension-candidate-chunks" could be added ? Useful debug ! 
In any case, thanks for the mod ! Useful too !

**Comment by 0ptera** [comment]
Hello,
As far as I know expansion chunks overlay is not exposed in the API to be toggled by mods.

**Comment by d0ob** [comment]
Ah too bad =( 
( Well it's not like it is just three clicks away after all lol I feel like a lazy fk now I think of it xD )
Thanks for your quick answer ! =)
